import type { NextPage, GetServerSideProps } from "next";
import Head from "next/head";
import { Product } from "@/helpers/types";

//get data from api
type Props = {
 products: Array<Product>;
};

export const getServerSideProps: GetServerSideProps = async (context) => {
 try {
  const productsRequest = await fetch(`${process.env.API_URL}/api/products`);
  const products = await productsRequest.json();
  return {
   props: { products },
  };
 } catch (error: any) {
  return {
   props: { products: [] },
  };
 }
};

const Home: NextPage<Props> = ({ products }) => {
 return (
  <div>
   <Head>
    <title>M3 | Digital</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
   </Head>
  </div>
 );
};

export default Home;
